version: "2"

services:
  mongodb:
    container_name: mongodb_container
    image: blbsystem/mongo:3.4
    build: .
    restart: always
    environment:
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=blbsyst3m
      - MONGODB_APPLICATION_DATABASE=searcher
      - MONGODB_APPLICATION_USER=user
      - MONGODB_APPLICATION_PASS=blbsearch3r
    ports:
      - "27017:27017"
    volumes:
      - mongo-storage:/data/db
    networks:
      - mongo-tier

networks:
  mongo-tier:
    driver: bridge

volumes:
  mongo-storage:
    driver: local